server:
  port: 8080

jwt:
  issuer: "dev-note"
  expiration-seconds: 36000

spring:
  application:
    name: dev-note

  security:
    oauth2:
      resourceserver:
        jwt:

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # dev에서만 사용
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  cache:
    cache-names: noteById
    redis:
      time-to-live: 10m
      key-prefix: "devnote:"
      cache-null-values: false

logging:
  level:
    org.hibernate.SQL: debug
